Interface:
    orientation: "vertical"
    padding:[dp(20),dp(20),dp(20),dp(20)]
    spacing:dp(20)

    Label:
        text: "Sentiment Analyzer"
        size_hint_y:None
        height:dp(50)

    TextInput:
        size_hint:1,0.6

    BoxLayout:
        size_hint:1,0.1
        spacing:dp(20)
        Button:
            text: "Analyzer"
        Button:
            text: "Clear"

    Label:
        size_hint: 1,0.3
        text: "Result"
